mearge: input 개발
EntryDSM/EntryDesignSystem pull request #2
Opened 2023-01-09 10:32 UTC by kimjh11130

2023-01-13 04:04 UTC, kimulchan requested changes
수고했어 코멘트 달아놓은거 확인해봐!

2023-01-13 04:19 UTC, kimjh11130 commented on src/components/Input.tsx
> +
수정했습니다.

2023-01-13 04:19 UTC, kimjh11130 commented on src/components/Input.tsx
> +}
수정했습니다. 그리고 disabled는 피그마에는 없었어요

2023-01-13 04:19 UTC, kimjh11130 commented on src/components/Input.tsx
> +`;
수정했습니다.

2023-01-13 04:22 UTC, kimjh11130 commented on src/components/Input.tsx
> +                    placeholder={isClick ? '' : placeholder}
수정했습니다.

2023-01-13 04:22 UTC, kimjh11130 commented on src/components/Input.tsx
> +`;
수정했습니다.

2023-01-17 02:25 UTC, kimulchan commented
tsconfig 들어가서 stories 파일 다 exclude해봐바

2023-01-17 02:26 UTC, kimulchan commented
그러면 아마 로컬 내부에서는 오류 나는데 빌드에서는 안터질거야

2023-01-20 06:58 UTC, merged